apiVersion: apps/v1
kind: Deployment
metadata:
  name: glowcare
  namespace: glowcare
  labels:
    app.kubernetes.io/name: glowcare
    app.kubernetes.io/component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: glowcare
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: glowcare
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: glowcare
          image: markomijoski/creamshop:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: glowcare-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: glowcare-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: glowcare-secret
                  key: DB_PASSWORD
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: glowcare-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: glowcare-config
                  key: DB_PORT
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: glowcare-secret
                  key: SECRET_KEY
            - name: DEBUG
              value: "False"
            - name: ALLOWED_HOSTS
              value: "*"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          startupProbe:
            httpGet:
              path: /healthz/
              port: http
              scheme: HTTP
              httpHeaders:
              - name: Host
                value: localhost # или вашиот домен
            periodSeconds: 10
            failureThreshold: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz/
              port: http
              scheme: HTTP
              httpHeaders:
              - name: Host
                value: localhost # или вашиот домен
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz/
              port: http
              scheme: HTTP
              httpHeaders:
              - name: Host
                value: localhost # или вашиот домен
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3