apiVersion: v1
kind: Service
metadata:
  name: glowcare
  namespace: glowcare
  labels:
    app.kubernetes.io/name: glowcare
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: glowcare
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: 80
      targetPort: 8000
