apiVersion: v1
kind: Secret
metadata:
  name: glowcare-secret
  namespace: glowcare
  labels:
    app.kubernetes.io/name: glowcare
    app.kubernetes.io/component: backend
type: Opaque
stringData:
  DB_USER: PLACEHOLDER
  DB_PASSWORD: PLACEHOLDER
  SECRET_KEY: PLACEHOLDER
